// <auto-generated />
using System;
using HoopLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoopLog.Migrations
{
    [DbContext(typeof(HoopLogDbContext))]
    partial class HoopLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HoopLog.Data.Models.Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Description = "Shoot free throws from the line, track makes out of attempts.",
                            Name = "Free Throws"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "Shoot from five fixed spots around the arc.",
                            Name = "Spot-Up Jumpers"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Description = "Weave through cones using both hands.",
                            Name = "Cone Dribbling"
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            Description = "Sprint down and back at increasing distances.",
                            Name = "Suicides"
                        },
                        new
                        {
                            Id = 5,
                            Category = 4,
                            Description = "Lateral slides in a defensive stance.",
                            Name = "Defensive Slides"
                        },
                        new
                        {
                            Id = 6,
                            Category = 3,
                            Description = "Bodyweight strength circuit.",
                            Name = "Core Circuit"
                        });
                });

            modelBuilder.Entity("HoopLog.Data.Models.DrillResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Attempts")
                        .HasColumnType("int");

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<int?>("DrillId1")
                        .HasColumnType("int");

                    b.Property<int?>("Makes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.HasIndex("DrillId1");

                    b.HasIndex("SessionId");

                    b.ToTable("DrillResults");
                });

            modelBuilder.Entity("HoopLog.Data.Models.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("HoopLog.Data.Models.DrillResult", b =>
                {
                    b.HasOne("HoopLog.Data.Models.Drill", "Drill")
                        .WithMany()
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoopLog.Data.Models.Drill", null)
                        .WithMany("DrillResults")
                        .HasForeignKey("DrillId1");

                    b.HasOne("HoopLog.Data.Models.TrainingSession", "TrainingSession")
                        .WithMany("DrillResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("HoopLog.Data.Models.Drill", b =>
                {
                    b.Navigation("DrillResults");
                });

            modelBuilder.Entity("HoopLog.Data.Models.TrainingSession", b =>
                {
                    b.Navigation("DrillResults");
                });
#pragma warning restore 612, 618
        }
    }
}
